-- MySQL Script generated by MySQL Workbench
-- qui 21 nov 2024 10:34:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NotaFiscal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NotaFiscal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NotaFiscal` ;
USE `NotaFiscal` ;

-- -----------------------------------------------------
-- Table `NotaFiscal`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaFiscal`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `acesso` ENUM("cliente", "estabelecimento", "admin") NULL,
  `pontos_usuario` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaFiscal`.`Registro_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaFiscal`.`Registro_Compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_estabelecimento` INT NOT NULL,
  `preco` FLOAT NULL,
  `data` DATE NULL,
  `pontos_compra` INT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_Registro_Compra_Usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Registro_Compra_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `NotaFiscal`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
