show databases;
use empresa;
show tables;
describe descontos;
select * from descontos;
select * from empregados;
select * from pagamentos;
select codigo_empregado, valor from pagamentos;
select codigo_empregado AS codigo, valor from pagamentos;
select codigo_empregado as codigo, valor as 'valor em reais' from pagamentos;
select count(nome) from empregados;
select sum(valor) from pagamentos;
select * from pagamentos where valor>400;
select codigo_empregado as codigo, valor from pagamentos where valor>400;
select sum(valor) from pagamentos where codigo_empregado=1;
select codigo_empregado, sum(valor) from pagamentos group by codigo_empregado;
select codigo_empregado, avg(valor) from pagamentos group by codigo_empregado;
select codigo_empregado AS codigo, avg(valor) AS media from pagamentos group by codigo_empregado;
select codigo_empregado AS codigo, max(valor) AS 'Mximo Valor', min(Valor) AS 'Valor Minimo' from pagamentos group by codigo_empregado;

use world;
show tables;
describe Country;
select Name,Population from City;
select Code, Name, Continent from Country;
select Code, Name, Continent from Country LIMIT 5;
select Code, Name, Continent from Country order by Code DESC;
select Name,Population from City where countrycode='bra';
select Name,Population from Country order by population desc limit 10;
select Name,SurfaceArea from Country order by SurfaceArea ASC ;
select Name,SurfaceArea from Country order by SurfaceArea ASC LIMIT 5;
select Name,SurfaceArea from Country order by SurfaceArea DESC LIMIT 5;
select count(Name) from Country;
select count(Name) from City;
select Continent, max(SurfaceArea) from Country GROUP BY Continent;
select Continent, sum(SurfaceArea) from Country GROUP BY Continent;
SELECT Name, Population FROM City WHERE Population > 1000000;
select Name,Capital from Country where Continent = "South America";
select Name,Capital,Code from Country order by Code ASC LIMIT 5;
select ID,Name,CountryCode from City order by CountryCode ASC LIMIT 5;
select row_number() over () ID, ci.name Capitals, co.name Country from City ci inner join Country co on ci.id = co.capital where co.continent = 'South America';
