-- MySQL Script generated by MySQL Workbench
-- qui 31 out 2024 09:09:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema` DEFAULT CHARACTER SET utf8 ;
USE `Sistema` ;

-- -----------------------------------------------------
-- Table `Sistema`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema`.`Banco` (
  `idBanco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NULL,
  `codigo` INT NULL,
  `endereco` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `numeroAgencias` INT NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema`.`Agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema`.`Agencia` (
  `idAgencia` INT NOT NULL AUTO_INCREMENT,
  `idBanco` INT NOT NULL,
  `codigo` INT NULL,
  `endereco` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idAgencia`, `idBanco`),
  INDEX `fk_Agencia_Banco_idx` (`idBanco` ASC) VISIBLE,
  CONSTRAINT `fk_Agencia_Banco`
    FOREIGN KEY (`idBanco`)
    REFERENCES `Sistema`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `cpf` VARCHAR(45) NULL,
  `genero` ENUM("m", "f") NULL,
  `dataNasc` DATE NULL,
  `edereco` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema`.`Conta` (
  `idConta` INT NOT NULL AUTO_INCREMENT,
  `idAgencia` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `saldo` FLOAT NULL,
  PRIMARY KEY (`idConta`, `idAgencia`),
  INDEX `fk_Conta_Agencia1_idx` (`idAgencia` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Agencia1`
    FOREIGN KEY (`idAgencia`)
    REFERENCES `Sistema`.`Agencia` (`idAgencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema`.`Cliente_Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema`.`Cliente_Conta` (
  `idCliente` INT NOT NULL,
  `idConta` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idConta`),
  INDEX `fk_Cliente_has_Conta_Conta1_idx` (`idConta` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Conta_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Conta_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Sistema`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Conta_Conta1`
    FOREIGN KEY (`idConta`)
    REFERENCES `Sistema`.`Conta` (`idConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
