-- MySQL Script generated by MySQL Workbench
-- qua 07 ago 2024 10:39:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AMP_CIA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AMP_CIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AMP_CIA` DEFAULT CHARACTER SET utf8 ;
USE `AMP_CIA` ;

-- -----------------------------------------------------
-- Table `AMP_CIA`.`Regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Regiao` (
  `ID` INT NOT NULL,
  `Continente` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Escritorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Escritorio` (
  `ID` INT NOT NULL,
  `ID_Regiao` INT NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`, `ID_Regiao`),
  INDEX `fk_Escritorio_Regiao1_idx` (`ID_Regiao` ASC) VISIBLE,
  CONSTRAINT `fk_Escritorio_Regiao1`
    FOREIGN KEY (`ID_Regiao`)
    REFERENCES `AMP_CIA`.`Regiao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Empregado` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Data_Nasc` DATE NULL,
  `Sexo` ENUM('F', 'M') NULL,
  `Data_Contratacao` DATE NULL,
  `Escritorio_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Escritorio_ID`),
  INDEX `fk_Empregado_Escritorio1_idx` (`Escritorio_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Empregado_Escritorio1`
    FOREIGN KEY (`Escritorio_ID`)
    REFERENCES `AMP_CIA`.`Escritorio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Cargo` (
  `ID` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Salario` DOUBLE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Departamento` (
  `ID` INT NOT NULL,
  `Setor` VARCHAR(45) NULL,
  `Qntd_Empregados` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Curso` (
  `ID` INT NOT NULL,
  `Area` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Duracao_Horas` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Acionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Acionista` (
  `Tipo_Pessoa` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Partição` VARCHAR(45) NULL,
  `CNPJ/CPF` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Assistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Assistencia` (
  `ID` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Dependente` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Parentesco` VARCHAR(45) NULL,
  `Idade` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Qualificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Qualificacao` (
  `ID_Emp` INT NOT NULL,
  `ID_Curso` INT NOT NULL,
  `Status` ENUM("Completo", "Incompleto", "Em curso") NULL,
  PRIMARY KEY (`ID_Emp`, `ID_Curso`),
  INDEX `fk_Empregado_has_Curso_Curso1_idx` (`ID_Curso` ASC) VISIBLE,
  INDEX `fk_Empregado_has_Curso_Empregado_idx` (`ID_Emp` ASC) VISIBLE,
  CONSTRAINT `fk_Empregado_has_Curso_Empregado`
    FOREIGN KEY (`ID_Emp`)
    REFERENCES `AMP_CIA`.`Empregado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empregado_has_Curso_Curso1`
    FOREIGN KEY (`ID_Curso`)
    REFERENCES `AMP_CIA`.`Curso` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Lotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Lotacao` (
  `ID_Emp` INT NOT NULL,
  `ID_Depto` INT NOT NULL,
  `ID_Cargo` INT NOT NULL,
  PRIMARY KEY (`ID_Emp`, `ID_Depto`, `ID_Cargo`),
  INDEX `fk_Cargo_has_Departamento_Departamento1_idx` (`ID_Depto` ASC) VISIBLE,
  INDEX `fk_Cargo_has_Departamento_Cargo1_idx` (`ID_Emp` ASC) VISIBLE,
  INDEX `fk_Cargo_has_Departamento_Empregado1_idx` (`ID_Cargo` ASC) VISIBLE,
  UNIQUE INDEX `ID_Emp_UNIQUE` (`ID_Emp` ASC) VISIBLE,
  CONSTRAINT `fk_Cargo_has_Departamento_Cargo1`
    FOREIGN KEY (`ID_Emp`)
    REFERENCES `AMP_CIA`.`Cargo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_has_Departamento_Departamento1`
    FOREIGN KEY (`ID_Depto`)
    REFERENCES `AMP_CIA`.`Departamento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_has_Departamento_Empregado1`
    FOREIGN KEY (`ID_Cargo`)
    REFERENCES `AMP_CIA`.`Empregado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AMP_CIA`.`Beneficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AMP_CIA`.`Beneficio` (
  `ID_Emp` INT NOT NULL,
  `ID_Assistencia` INT NOT NULL,
  `ID_Dependente` INT NOT NULL,
  PRIMARY KEY (`ID_Assistencia`, `ID_Dependente`, `ID_Emp`),
  INDEX `fk_Empregado_has_Assistencia_Assistencia1_idx` (`ID_Assistencia` ASC) VISIBLE,
  INDEX `fk_Empregado_has_Assistencia_Empregado1_idx` (`ID_Emp` ASC) VISIBLE,
  INDEX `fk_Empregado_has_Assistencia_Dependente1_idx` (`ID_Dependente` ASC) VISIBLE,
  CONSTRAINT `fk_Empregado_has_Assistencia_Empregado1`
    FOREIGN KEY (`ID_Emp`)
    REFERENCES `AMP_CIA`.`Empregado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empregado_has_Assistencia_Assistencia1`
    FOREIGN KEY (`ID_Assistencia`)
    REFERENCES `AMP_CIA`.`Assistencia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empregado_has_Assistencia_Dependente1`
    FOREIGN KEY (`ID_Dependente`)
    REFERENCES `AMP_CIA`.`Dependente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
